export const MEDIA_GET = 'media:get'
export const MEDIA_ADD = 'media:add'
export const MEDIA_REMOVE = 'media:remove'
export const MEDIA_UPDATE = 'media:update'
export const MEDIA_SET_NEXT_MEDIA = 'media:set-next-media'
export const MEDIA_RESOLVE_EXTERNAL_LINK = 'media:resolve-external-link'
export const MEDIA_SEARCH = 'media:search'
export const MEDIA_GET_BY_ID = 'media:get-by-id'
